dependencies:
- name: postgresql
  version: 0.8.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: rabbitmq
  version: 2.1.2
  repository: https://kubernetes-charts.storage.googleapis.com/