image:
  repository: gcr.io/njcoast-174716/django
  tag: test

imagePullPolicy: Always

service:
  type: NodePort
  internalPort: 8000
  externalPort: 8000

ingress:
  enabled: true
  hosts:
    - njcoast.local
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  # existingClaim:

aws:
  id: "AWSID"
  key: "AWSKEY"

simulation:
  location: "https://s3.amazonaws.com/simulation.njcoast.us"
  path: "simulation"

queue:
  image:
    repository: simulation-queue
    tag: latest
    # secret: 
    pullPolicy: Always

  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  
  worker:
    image:
      repository: simulation-queue
      tag: worker
      # secret: 
      pullPolicy: Always

    resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

    autoscale:
      enabled: false
      minimum: 1
      maximum: 4
      targetcpu: 50

  service:
    type: ClusterIP

geoserver:
  image:
    repository: gcr.io/njcoast-174716/geoserver
    tag: test-2.10

  service:
    type: NodePort
    internalPort: 8080
    externalPort: 8080

  resources: {}

  persistence:
    enabled: false
    # existingClaim:
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 1Gi

postgresql:
  image: "postgres"
  imageTag: "9.6.2"

  postgresUser: postgres
  postgresPassword: test
  # postgresDatabase:

  persistence:
    enabled: false
    # existingClaim:
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi

  metrics:
    enabled: false

  resources:
    requests:
      memory: 256Mi
      cpu: 100m

  service:
    type: ClusterIP
    port: 5432

rabbitmq:
  rabbitmqUsername: user
  rabbitmqPassword: test
  rabbitmqNodePort: 5672

  serviceType: ClusterIP

  persistence:
    enabled: false