apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-aws
  labels:
    app: {{ template "fullname" . }}-aws
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.id | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.key | b64enc | quote }}