apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-queue-worker
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-queue-worker
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.queue.worker.image.secret }}
      imagePullSecrets: 
        - name: {{ .Values.queue.worker.image.secret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.queue.worker.image.repository }}:{{ .Values.queue.worker.image.tag }}"
        imagePullPolicy: {{ default "" .Values.queue.worker.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.queue.worker.resources | indent 10 }}
        env:
        - name: HTTP_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-aws
              key: USER_NAME
        - name: HTTP_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-aws
              key: USER_PASS
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-aws
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}-aws
              key: AWS_SECRET_ACCESS_KEY
        - name: SERVER_HOSTNAME
          value: {{ .Values.ingress.hosts | first }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name