apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-queue-worker
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-queue-worker
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.queue.worker.image.secret }}
      imagePullSecrets: 
        - name: {{ .Values.queue.worker.image.secret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.queue.worker.image.repository }}:{{ .Values.queue.worker.image.tag }}"
        imagePullPolicy: {{ default "" .Values.queue.worker.pullPolicy | quote }}
        resources:
{{ toYaml .Values.queue.resources | indent 10 }}
        env:
        - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: {{ .Release.Name }}-aws
            key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-aws
              key: AWS_SECRET_ACCESS_KEY