apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-celery
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.celery.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-celery
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.secret }}
      imagePullSecrets: 
        - name: {{ .Values.image.secret }}
      {{- end }}
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          command: ["/celary.sh"]
          envFrom:
          - configMapRef:
              name: {{ template "fullname" . }}-env
          env:
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          resources:
{{ toYaml .Values.celery.resources | indent 12 }}