apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-django
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-django
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.secret }}
      imagePullSecrets: 
        - name: {{ .Values.image.secret }}
      {{- end }}
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          command: ["/entrypoint.sh"]
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          volumeMounts:
          - name: uploads
            mountPath: /usr/local/src/geonode/geonode/uploaded
          - name: sitename-fixture
            mountPath: /app/njcoast/fixtures/sitename.yaml
            subPath: sitename.yaml
          envFrom:
          - configMapRef:
              name: {{ template "fullname" . }}-env
          env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: SECRET_KEY
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: SMTP_USERNAME
                optional: true
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: SMTP_PASSWORD
                optional: true
          - name: GEOSERVER_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: GEOSERVER_ADMIN_USER
                optional: true
          - name: GEOSERVER_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: GEOSERVER_ADMIN_PASSWORD
                optional: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: uploads
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
          {{- if .Values.persistence.existingClaim }}
            claimName: {{ .Values.persistence.existingClaim }}
          {{- else }}
            claimName: {{ template "fullname" . }}-uploads
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: sitename-fixture
          configMap:
             name: {{ template "fullname" . }}-data