apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-django
  labels:
    app: {{ template "fullname" . }}-django
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  SECRET_KEY: {{ default "myv-y4#7j-d*p-__@j#*3z@!y24fz8%^z2v6atuy4bo9vqr1_a" .Values.secretKey | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  GEOSERVER_ADMIN_USER: {{ .Values.geoserver.security.username | b64enc | quote }}
  GEOSERVER_ADMIN_PASSWORD: {{ .Values.geoserver.security.password | b64enc | quote }}