apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-worker
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-worker
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.image.secret }}
      imagePullSecrets: 
        - name: {{ .Values.image.secret }}
      {{- end }}
      containers:
        - name: celery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
          command: ["python", "/app/manage.py", "runworker"]
          envFrom:
          - configMapRef:
              name: {{ template "fullname" . }}-env
          env:
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-postgresql
                key: postgres-password
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: SMTP_USERNAME
                optional: true
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: SMTP_PASSWORD
                optional: true
          - name: GEOSERVER_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: GEOSERVER_ADMIN_USER
                optional: true
          - name: GEOSERVER_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}-django
                key: GEOSERVER_ADMIN_PASSWORD
                optional: true
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}